### ISSUE TITLE
Customize Page Title

### ISSUE THREAD

**Issue by Maschina** [helloideabox/smart-docs#5]
I have realized that the default page title is "Smart Docs Archive" in the category overview.

Can this be changed or does it need to be implemented?

**Comment by AchalJ** [comment]
@Maschina may I know which theme you are using?

**Comment by Maschina** [comment]
I am using the [Neve theme](https://themeisle.com)

**Comment by AchalJ** [comment]
I tested with the Neve theme and the category archive title is "Documentation" that's what saved in the SmartDocs settings as "Hero Title".

![image](https://user-images.githubusercontent.com/12668839/191027684-b550a090-23e5-4008-9d8e-22fdaaf55492.png)

**Comment by Maschina** [comment]
Sorry for not being precise enough. I do not mean the hero title, but the title of the browser window that is coded in <head>...<title>

**Comment by AchalJ** [comment]
You will need an SEO plugin to change the text of <title> tag. For example, if you use Yoast SEO then navigate to Yoast SEO > Search Appearance > Taxonomies and you will find the option to change the title for the SmartDocs category.
